version: '3'
services:
  db:
    image: postgres:15
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=CSxhAs9OECs/P1z2/DBJ7q9sOXdZbXzMWAnRJwf5g5k=
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

  odoo:
    image: odoo:18.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=CSxhAs9OECs/P1z2/DBJ7q9sOXdZbXzMWAnRJwf5g5k=
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data:
